#!/usr/bin/env bash

# turns the screen off and puts it into background mode
swayidle \
  timeout 300 'swaymsg "output * power off"' \
  resume 'swaymsg "output * power on"' &
# locks the screen immediately
swaylock
# kills last background task so idle timer doesn't keep running
kill %%
